export const COUNTRY_NAMES: Record<string, string> = {
  us: "United States", gb: "United Kingdom", ca: "Canada", au: "Australia",
  de: "Germany", fr: "France", es: "Spain", it: "Italy", nl: "Netherlands",
  ru: "Russia", ua: "Ukraine", pl: "Poland", se: "Sweden", fi: "Finland",
  ro: "Romania", id: "Indonesia", ph: "Philippines", br: "Brazil",
  mx: "Mexico", in: "India", jp: "Japan", kr: "South Korea", za: "South Africa",
  ar: "Argentina", cl: "Chile", co: "Colombia", pe: "Peru", th: "Thailand",
  vn: "Vietnam", tr: "Turkey", eg: "Egypt", ma: "Morocco", ng: "Nigeria",
  ke: "Kenya", pk: "Pakistan", bd: "Bangladesh", pt: "Portugal", gr: "Greece",
  cz: "Czech Republic", hu: "Hungary", be: "Belgium", at: "Austria", ch: "Switzerland",
  dk: "Denmark", no: "Norway", ie: "Ireland", nz: "New Zealand", sg: "Singapore",
  my: "Malaysia", hk: "Hong Kong", tw: "Taiwan", sa: "Saudi Arabia", ae: "UAE",
  il: "Israel", kz: "Kazakhstan", uz: "Uzbekistan", az: "Azerbaijan",
  ge: "Georgia", am: "Armenia", by: "Belarus", lt: "Lithuania", lv: "Latvia",
  ee: "Estonia", sk: "Slovakia", si: "Slovenia", hr: "Croatia", bg: "Bulgaria",
  rs: "Serbia", mk: "North Macedonia", al: "Albania", ba: "Bosnia", me: "Montenegro",
  ad: "Andorra", ag: "Antigua & Barbuda", ai: "Anguilla", ao: "Angola",
  aw: "Aruba", ax: "Åland Islands", bb: "Barbados",
  bf: "Burkina Faso", bi: "Burundi", bj: "Benin", bm: "Bermuda",
  bn: "Brunei", bo: "Bolivia", bs: "Bahamas", bw: "Botswana",
  bz: "Belize", cd: "DR Congo", cf: "Central African Rep.", cg: "Congo",
  ci: "Côte d'Ivoire", ck: "Cook Islands", cm: "Cameroon", cn: "China",
  cr: "Costa Rica", cu: "Cuba", cv: "Cape Verde", cw: "Curaçao",
  cy: "Cyprus", dj: "Djibouti", dm: "Dominica", do: "Dominican Rep.",
  ec: "Ecuador", er: "Eritrea", et: "Ethiopia",
  fj: "Fiji", fo: "Faroe Islands", ga: "Gabon", gd: "Grenada",
  gf: "French Guiana", gh: "Ghana", gi: "Gibraltar", gl: "Greenland",
  gm: "Gambia", gn: "Guinea", gp: "Guadeloupe", gq: "Equatorial Guinea",
  gt: "Guatemala", gw: "Guinea-Bissau", gy: "Guyana", hn: "Honduras",
  ht: "Haiti", is: "Iceland", jm: "Jamaica", jo: "Jordan",
  kh: "Cambodia", ki: "Kiribati", km: "Comoros", kn: "St. Kitts & Nevis",
  kp: "North Korea", kw: "Kuwait", ky: "Cayman Islands", la: "Laos",
  lb: "Lebanon", lc: "St. Lucia", li: "Liechtenstein", lr: "Liberia",
  ls: "Lesotho", lu: "Luxembourg", ly: "Libya", mc: "Monaco",
  md: "Moldova", mg: "Madagascar", mh: "Marshall Islands", ml: "Mali",
  mm: "Myanmar", mn: "Mongolia", mo: "Macau", mq: "Martinique",
  mr: "Mauritania", ms: "Montserrat", mt: "Malta", mu: "Mauritius",
  mv: "Maldives", mw: "Malawi", mz: "Mozambique", na: "Namibia",
  nc: "New Caledonia", ne: "Niger", nf: "Norfolk Island", ni: "Nicaragua",
  np: "Nepal", nr: "Nauru", nu: "Niue", om: "Oman",
  pw: "Palau", pa: "Panama", pg: "Papua New Guinea", py: "Paraguay",
  pm: "St. Pierre & Miquelon", pn: "Pitcairn", pr: "Puerto Rico",
  ps: "Palestine", qa: "Qatar", re: "Réunion",
  rw: "Rwanda", sb: "Solomon Islands", sc: "Seychelles", sd: "Sudan",
  sh: "St. Helena", sl: "Sierra Leone", sm: "San Marino", sn: "Senegal",
  so: "Somalia", sr: "Suriname", ss: "South Sudan", st: "São Tomé & Príncipe",
  sv: "El Salvador", sx: "Sint Maarten", sy: "Syria", sz: "Eswatini",
  tc: "Turks & Caicos", td: "Chad", tg: "Togo", tj: "Tajikistan",
  tk: "Tokelau", tl: "Timor-Leste", tm: "Turkmenistan", tn: "Tunisia",
  to: "Tonga", tt: "Trinidad & Tobago", tv: "Tuvalu", tz: "Tanzania",
  ug: "Uganda", uy: "Uruguay", va: "Vatican City", vc: "St. Vincent",
  ve: "Venezuela", vg: "British Virgin Islands", vi: "U.S. Virgin Islands",
  vu: "Vanuatu", wf: "Wallis & Futuna", ws: "Samoa", ye: "Yemen",
  zm: "Zambia", zw: "Zimbabwe",
};

export const COUNTRY_FLAGS: Record<string, string> = {
  us: "🇺🇸", gb: "🇬🇧", ca: "🇨🇦", au: "🇦🇺", de: "🇩🇪", fr: "🇫🇷",
  es: "🇪🇸", it: "🇮🇹", nl: "🇳🇱", ru: "🇷🇺", ua: "🇺🇦", pl: "🇵🇱",
  se: "🇸🇪", fi: "🇫🇮", ro: "🇷🇴", id: "🇮🇩", ph: "🇵🇭", br: "🇧🇷",
  mx: "🇲🇽", in: "🇮🇳", jp: "🇯🇵", kr: "🇰🇷", za: "🇿🇦", ar: "🇦🇷",
  cl: "🇨🇱", co: "🇨🇴", pe: "🇵🇪", th: "🇹🇭", vn: "🇻🇳", tr: "🇹🇷",
  eg: "🇪🇬", ma: "🇲🇦", ng: "🇳🇬", ke: "🇰🇪", pk: "🇵🇰", bd: "🇧🇩",
  pt: "🇵🇹", gr: "🇬🇷", cz: "🇨🇿", hu: "🇭🇺", be: "🇧🇪", at: "🇦🇹",
  ch: "🇨🇭", dk: "🇩🇰", no: "🇳🇴", ie: "🇮🇪", nz: "🇳🇿", sg: "🇸🇬",
  my: "🇲🇾", hk: "🇭🇰", tw: "🇹🇼", sa: "🇸🇦", ae: "🇦🇪", il: "🇮🇱",
  kz: "🇰🇿", uz: "🇺🇿", az: "🇦🇿", ge: "🇬🇪", am: "🇦🇲", by: "🇧🇾",
  lt: "🇱🇹", lv: "🇱🇻", ee: "🇪🇪", sk: "🇸🇰", si: "🇸🇮", hr: "🇭🇷",
  bg: "🇧🇬", rs: "🇷🇸", mk: "🇲🇰", al: "🇦🇱", ba: "🇧🇦", me: "🇲🇪",
  ad: "🇦🇩", ag: "🇦🇬", ao: "🇦🇴", aw: "🇦🇼", bb: "🇧🇧", bf: "🇧🇫",
  bi: "🇧🇮", bj: "🇧🇯", bm: "🇧🇲", bn: "🇧🇳", bo: "🇧🇴", bs: "🇧🇸",
  bw: "🇧🇼", bz: "🇧🇿", cd: "🇨🇩", cf: "🇨🇫", cg: "🇨🇬", ci: "🇨🇮",
  ck: "🇨🇰", cm: "🇨🇲", cn: "🇨🇳", cr: "🇨🇷", cu: "🇨🇺", cv: "🇨🇻",
  cw: "🇨🇼", cy: "🇨🇾", dj: "🇩🇯", dm: "🇩🇲", do: "🇩🇴", ec: "🇪🇨",
  er: "🇪🇷", et: "🇪🇹", fj: "🇫🇯", fo: "🇫🇴", ga: "🇬🇦", gd: "🇬🇩",
  gf: "🇬🇫", gh: "🇬🇭", gi: "🇬🇮", gl: "🇬🇱", gm: "🇬🇲", gn: "🇬🇳",
  gp: "🇬🇵", gq: "🇬🇶", gt: "🇬🇹", gw: "🇬🇼", gy: "🇬🇾", hn: "🇭🇳",
  ht: "🇭🇹", is: "🇮🇸", jm: "🇯🇲", jo: "🇯🇴", kh: "🇰🇭", ki: "🇰🇮",
  km: "🇰🇲", kn: "🇰🇳", kp: "🇰🇵", kw: "🇰🇼", ky: "🇰🇾", la: "🇱🇦",
  lb: "🇱🇧", lc: "🇱🇨", li: "🇱🇮", lr: "🇱🇷", ls: "🇱🇸", lu: "🇱🇺",
  ly: "🇱🇾", mc: "🇲🇨", md: "🇲🇩", mg: "🇲🇬", mh: "🇲🇭", ml: "🇲🇱",
  mm: "🇲🇲", mn: "🇲🇳", mo: "🇲🇴", mq: "🇲🇶", mr: "🇲🇷", ms: "🇲🇸",
  mt: "🇲🇹", mu: "🇲🇺", mv: "🇲🇻", mw: "🇲🇼", mz: "🇲🇿", na: "🇳🇦",
  nc: "🇳🇨", ne: "🇳🇪", nf: "🇳🇫", ni: "🇳🇮", np: "🇳🇵", nr: "🇳🇷",
  nu: "🇳🇺", om: "🇴🇲", pw: "🇵🇼", pa: "🇵🇦", pg: "🇵🇬", py: "🇵🇾",
  pm: "🇵🇲", pn: "🇵🇳", pr: "🇵🇷", ps: "🇵🇸", qa: "🇶🇦", re: "🇷🇪",
  rw: "🇷🇼", sb: "🇸🇧", sc: "🇸🇨", sd: "🇸🇩", sh: "🇸🇭", sl: "🇸🇱",
  sm: "🇸🇲", sn: "🇸🇳", so: "🇸🇴", sr: "🇸🇷", ss: "🇸🇸", st: "🇸🇹",
  sv: "🇸🇻", sx: "🇸🇽", sy: "🇸🇾", sz: "🇸🇿", tc: "🇹🇨", td: "🇹🇩",
  tg: "🇹🇬", tj: "🇹🇯", tk: "🇹🇰", tl: "🇹🇱", tm: "🇹🇲", tn: "🇹🇳",
  to: "🇹🇴", tt: "🇹🇹", tv: "🇹🇻", tz: "🇹🇿", ug: "🇺🇬", uy: "🇺🇾",
  va: "🇻🇦", vc: "🇻🇨", ve: "🇻🇪", vg: "🇻🇬", vi: "🇻🇮", vu: "🇻🇺",
  wf: "🇼🇫", ws: "🇼🇸", ye: "🇾🇪", zm: "🇿🇲", zw: "🇿🇼",
};

export function getCountryName(code: string): string {
  return COUNTRY_NAMES[code.toLowerCase()] || code.toUpperCase();
}

export function getCountryFlag(code: string): string {
  return COUNTRY_FLAGS[code.toLowerCase()] || "🏳️";
}
